var Alexa = require('alexa-sdk');
var Data = require("./data");
var https = require('https');
var Client = require('node-rest-client').Client;
var client = new Client();
var Promise = require('promise');
//Mohd
//  var AWS = require("aws-sdk")
// AWS.config.update({
//     accessKeyId: "AKIAJDAF6FJ6V22KD6VA",
//     secretAccessKey: "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",
//   region: "us-east-1",
//   // endpoint: "http://localhost:8000"
// });

// var docClient = new AWS.DynamoDB.DocumentClient()

// var table = "Partition";

// var id = 2;

// var params = {
//     TableName: table,
//     Key:{
//         "id": id
//     }
// };

// docClient.get(params, function(err, data) {
//     if (err) {
//         console.error("Unable to read item. Error JSON:", JSON.stringify(err, null, 2));
//     } else {
//         console.log("GetItem succeeded:", JSON.stringify(data, null, 2));
//     }
// });
// var AWS = require("aws-sdk");

// AWS.config.update({
//     accessKeyId: "AKIAJDAF6FJ6V22KD6VA",
//     secretAccessKey: "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",
//   region: "us-west-2",
//   endpoint: "http://localhost:8000"
// });

// var docClient = new AWS.DynamoDB.DocumentClient();

// var table = "Movies";

// var year = 2015;
// var title = "The Big New Movie";

// var params = {
//     TableName:table,
//     Item:{
//         "year": year,
//         "title": title,
//         "info":{
//             "plot": "Nothing happens at all.",
//             "rating": 0
//         }
//     }
// };

// console.log("Adding a new item...");
// docClient.put(params, function(err, data) {
//     if (err) {
//         console.error("Unable to add item. Error JSON:", JSON.stringify(err, null, 2));
//     } else {
//         console.log("Added item:", JSON.stringify(data, null, 2));
//     }
// });
 //Mohd
const skillName = "Elixir";
var currentSymptom = [];
var finalDisease = "";
var handlers = {

    "DiseaseIntent": function () {
        var self = this;
       if(this.event.request.intent.slots.Disease.value && this.event.request.intent.slots.Disease.value.toLowerCase() !== " "&& symptomsMapping[this.event.request.intent.slots.Disease.value.toLowerCase()] != undefined) {
        var speechOutput = "";

        currentSymptom.push(this.event.request.intent.slots.Disease.value.toLowerCase());

        var post_data =
        {
                "sex": "male",
                "age": 30,
                "evidence": []
            };

        for(var i = (currentSymptom.length - 1); i >= 0 ;i--){
            post_data.evidence.push({'id':symptomsMapping[currentSymptom[i]],'choice_id':'present'});
        }

        console.log(post_data);

        var args = {
            headers: {
                "App-Id": "7a7139ff",
                "App-Key": "f7754baf7ecdc339eca07ac15619e12b",
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(JSON.stringify(post_data))
            },
            data : JSON.stringify(post_data)
        }
        var newpromise = new Promise(function(resolve,reject){

                client.post('https://api.infermedica.com/v2/diagnosis',args,function(data,response){
                speechOutput =  "You may have "+ data.conditions[0].name+"       anymore symptoms";
                finalDisease = data.conditions[0].name;
                resolve(speechOutput);
            //console.log(speechOutput);

            })
        }


        );
//         var post_options = {
//             url:  'https://learnwebcode.github.io',
//             //port: '443',
//             path: '/json-example/animals-1.json',
//             method: 'GET',
//             // headers: {
//             //     "App-Id": "7a7139ff",
//             //     "App-Key": "f7754baf7ecdc339eca07ac15619e12b",
//             //     'Content-Type': 'application/json',
//             //     'Content-Length': Buffer.byteLength(JSON.stringify(post_data))
//             // },
//             //data: JSON.stringify(post_data)
//         };

//         var post_req = https.request(post_options, function(res) {
//             res.setEncoding('utf8');

//             res.on('data', function (chunk) {
//                 speechOutput += chunk;
//                 console.log(speechOutput);
//             });
//             res.on('end', function () {
//                 console.log('speechOutput: ' + speechOutput);

//                 console.log(JSON.parse(speechOutput));
//                 this.emit(':tellWithCard', speechOutput, skillName, speechOutput);

//             });

// });

//     post_req.write(JSON.stringify(post_data));
//     post_req.end();
       //this.emit(':tellWithCard', speechOutput, skillName, speechOutput);
       newpromise.then(
           function(){
               console.log(speechOutput);
               var repromptText = "Anymore symptoms?";
               self.emit(':saveState', true);
               self.attributes['name'] = 'santi';
               self.emit(':ask', speechOutput, skillName, repromptText);
            });
       }else{
           self.attributes['name'] = 'santi';
           self.emit(':saveState', true);
           speechOutput = "I didn't get you this time. Can you please try again";
           var repromptText = "I didn't get you this time. Can you please try again";
           self.emit(':ask', speechOutput, skillName, repromptText);
       }
    },
    "AMAZON.YesIntent": function() {

        this.attributes["name"] = 'santi';
        this.emit(':saveState', true);
        //this.handler.state = states.GUESSMODE;

        this.emit(':ask', 'Okay! ' + 'Please tell me the symptom', 'For instructions on what you can say, please say help me.');

    },
    "AMAZON.NoIntent": function() {
        this.emit(':ask', 'Ok what do you want me to do then?');
    },
    "AboutIntent": function () {
        this.attributes['name'] = 'santi';
        this.emit(':saveState', true);
        var repromptText = "For instructions on what you can say, please say help me.";
        this.emit(':ask', speechOutput, skillName, repromptText);
    },

    "AMAZON.HelpIntent": function () {
        var speechOutput = "";
        speechOutput += "Here are some things you can say: ";
        speechOutput += "Tell me something interesting about Java. ";
        speechOutput += "I have symptoms like head ache";
        speechOutput += "I'm feeling a bit unwell.";
        speechOutput += "So how can I help?";
        this.emit(':saveState', true);
        this.attributes['name'] = 'santi';

        this.emit(':ask', speechOutput, skillName, speechOutput);
    },

    "AMAZON.StopIntent": function () {
        var speechOutput = "Goodbye";

           this.emit(':tellWithCard', speechOutput, skillName, speechOutput);
    },

    "AMAZON.CancelIntent": function () {
        var speechOutput = "Goodbye";
           this.emit(':tellWithCard', speechOutput, skillName, speechOutput);
    },
    "DoctorIntent":function(){
        var self = this;
        var doctorsBio = "";
        var apiURL = "https://api.betterdoctor.com/2016-03-01/doctors";
        var user_key = "ebd74586afe46d9701cfb232d6cedd53";
        if(diseaseMapping[finalDisease] == undefined){
            var condition = "diagnosis";
            var i =  parseInt((Math.random() * (10 - 1) + 1)-1);
        }else{
          var condition= diseaseMapping[finalDisease]
          var i = 0;
        }
        var args = {
            parameters: {
                "user_key":user_key,
                "query": condition,
                "sort":'rating-desc',
                'Content-Type': 'application/json'
            }
        }
        var anotherpromise = new Promise(function(resolve,reject){
            client.get(apiURL,args,function(data,response){
            var doctors = data.data;

            var name = doctors[i].profile.title + " "
            name += doctors[i].profile.first_name + " "
            name += doctors[i].profile.last_name ;


            var aboutSpeciality = doctors[i].specialties[0].name;
            if(aboutSpeciality !== undefined){
            doctorsBio += name + " and the doctor specializes in " + aboutSpeciality;
            }else{
                doctorsBio += name;
            }
            resolve(doctorsBio);
            //console.log(doctorsBio);

            });
        });
        anotherpromise.then(
           function(){
               console.log(doctorsBio);
               var repromptText = "Hope you get well soon!";
               self.emit(':saveState', true);
               self.attributes['name'] = 'santi';
               doctorsBio = doctorsBio.replace("&","and")
               self.emit(':ask', doctorsBio, skillName, repromptText);
            });
    },
    'Unhandled': function() {
        var message = "I didn't get you this time. Can you please try again";
        this.emit(':saveState', true);
        this.attributes['name'] = 'santi';
        this.emit(':ask', message, message);
    },
    "LaunchRequest": function () {
        currentSymptom = [];
        var speechText = "";
        speechText += "Hi there I'm " + " " + skillName +"     " + " I will be your personal health assistant from now on! ";
        speechText += "How are you feeling today? ";
        var repromptText = "For instructions on what you can say, please say help me.";
        this.emit(':responseReady');
        this.attributes['name'] = 'santi';
        this.emit(':saveState', true); // Handles saving the contents of this.attributes and the current handler state to DynamoDB and then sends the previously built response to the Alexa service. Override if you wish to use a different persistence provider. The second attribute is optional and can be set to 'true' to force saving.

        //this.emit(':saveStateError');
        this.emit(':ask', speechText, repromptText);
    }

};

exports.handler = function (event, context) {
    var alexa = Alexa.handler(event, context);
    alexa.appId = "amzn1.ask.skill.02c289f6-9161-4b6d-ac5d-401e0a3c278e";
    alexa.registerHandlers(handlers);
    alexa.dynamoDBTableName = "PatientSession";
    alexa.execute();
};

var symptomsMapping = {
	"abdominal distension": "s_277",
	"abdominal guarding": "s_1558",
	"abdominal pain": "s_13",
	"abdominal pain, before menstrual period, cycle": "s_17",
	"abdominal pain, chronic": "s_18",
	"abdominal pain, epigastric": "s_1387",
	"abdominal pain, exacerbating after caffeine consumption": "s_1207",
	"abdominal pain, exacerbating during coughing or movement": "s_15",
	"abdominal pain, exacerbating during deep breath": "s_1202",
	"abdominal pain, exacerbating on an empty stomach": "s_14",
	"abdominal pain, flare-ups and remissions": "s_1187",
	"abdominal pain, increasing after a meal": "s_16",
	"abdominal pain, reduced by defecation or relieving flatulence": "s_57",
	"abdominal pain, right upper quadrant": "s_1528",
	"abdominal pain, right upper quadrant, exacerbated by deep inhalation": "s_567",
	"abdominal pain, severe": "s_1195",
	"abdominal pain, sharp, stabbing": "s_1369",
	"abdominal pain, sudden": "s_12",
	"abdominal tenderness": "s_1514",
	"abdominal tenderness, lower": "s_1400",
	"abdominal tumor after pregnancy or the removal of molar pregnancy": "s_1293",
	"abnormal foveal avascular zone": "s_1419",
	"absence of deep reflexes": "s_1072",
	"absent or decreased knee reflex": "s_1340",
	"achilles tendon hyper-reflexia": "s_1502",
	"activity related to sex despite negative consequences (failed relationships, health risks)": "s_3",
	"adenoid face": "s_1111",
	"aggravated by emotional stress": "s_559",
	"aggravated by humidity, heat": "s_391",
	"agitation": "s_145",
	"agnosia": "s_833",
	"agoraphobia": "s_884",
	"agraphia": "s_1012",
	"alcohol craving": "s_817",
	"alcohol tolerance": "s_588",
	"alcohol withdrawal syndrome": "s_818",
	"alcohol-related amnesia": "s_825",
	"allelomimetic behavior, allomimetic behavior": "s_1019",
	"allen-cleckley sign": "s_1272",
	"amenorrhea": "s_1457",
	"amenorrhea for at least 12 months": "s_1370",
	"amenorrhea, primary": "s_1458",
	"amenorrhea, secondary": "s_1459",
	"amusia": "s_1032",
	"angular cheilitis": "s_608",
	"anhedonia": "s_508",
	"anhidrosis": "s_1123",
	"anhidrosis, face, unilateral": "s_669",
	"anisocoria": "s_497",
	"ankle brachial index <0.9": "s_736",
	"anomic aphasia": "s_1030",
	"anorectal pain": "s_436",
	"anterior drawer sign": "s_1501",
	"anxiety (panic) attack": "s_582",
	"apathy": "s_4",
	"aphasia": "s_969",
	"aphonia": "s_477",
	"aphthous ulcers": "s_1",
	"aponeurotic reflex": "s_1269",
	"appetite for salty foods": "s_6",
	"apraxia": "s_1010",
	"arthropathy": "s_1292",
	"articular edema and pain of both hands or feet": "s_26",
	"ascending muscle weakness (starts in the legs and then spreads to the arms)": "s_744",
	"ascending paresthesias (paresthesias first in lower limbs and subsequently in upper limbs)": "s_1069",
	"ascites": "s_1116",
	"ataxia": "s_651",
	"atonic bladder, flaccid bladder": "s_1120",
	"atrophy of the interosseous muscles of the feet": "s_1084",
	"atrophy of the interosseous muscles of the hands": "s_1083",
	"auditory verbal agnosia": "s_1028",
	"auscultative crackles over the thorax": "s_855",
	"auscultative rales over the thorax": "s_857",
	"avoiding actions, places or people that bring back memories of trauma": "s_710",
	"avoiding eating and drinking in public": "s_718",
	"avoiding eating in someone's presence": "s_719",
	"avoiding public appearances": "s_717",
	"avoiding talking to authority figures": "s_720",
	"avoiding thoughts, feelings, conversations related to traumatic experience": "s_709",
	"axillary or inguinal freckles": "s_1322",
	"babinski sign": "s_1023",
	"back pain": "s_1190",
	"back pain, exacerbating after physical exertion": "s_159",
	"back pain, flare-ups and remissions": "s_1189",
	"back pain, lasting at least a few hours": "s_1205",
	"back pain, lumbar": "s_53",
	"back pain, severe": "s_1192",
	"back pain, subsides during rest": "s_1206",
	"back pain, sudden": "s_1198",
	"behavior ignoring consequences and social norms": "s_842",
	"behavioral changes": "s_843",
	"belching": "s_561",
	"bilateral absence of achilles tendon reflex": "s_1073",
	"bilateral limb apraxia": "s_1011",
	"bilateral muscle paralysis": "s_1291",
	"bing sign": "s_1257",
	"binge eating attacks": "s_137",
	"bizarre delusion": "s_769",
	"black stools": "s_71",
	"bladder not emptying completely": "s_435",
	"bladder sphincter dysfunction": "s_1119",
	"bleeding after intercourse": "s_152",
	"bleeding from anus": "s_115",
	"bleeding gums": "s_111",
	"bleeding into joints": "s_1170",
	"bleeding into muscles": "s_1386",
	"blepharoptosis": "s_192",
	"blisters and sores in the mouth": "s_694",
	"blisters fester or dry to form honey-colored crust": "s_373",
	"blisters or erosion on penis": "s_197",
	"blisters recurring after sun exposure, when lips are chapped, during infections or menstrual period": "s_402",
	"blisters usually appearing around mouth or nose": "s_374",
	"bloating": "s_309",
	"blood in stool": "s_112",
	"blood in urine": "s_113",
	"blood pressure fluctuation": "s_749",
	"blunted affect": "s_771",
	"blurred vision": "s_500",
	"bone deformation": "s_1224",
	"bone pain": "s_612",
	"bony lumps near the affected joints": "s_577",
	"bowel and bladder incontinence": "s_1026",
	"bowel incontinence": "s_641",
	"bowel sounds, hyperactive, high-pitched": "s_1552",
	"bradycardia": "s_534",
	"breast tenderness": "s_1480",
	"breast tightness or pain": "s_609",
	"broken capillaries": "s_209",
	"brown nail discoloration": "s_1310",
	"bruises or petechiae": "s_234",
	"buccofacial or orofacial apraxia": "s_1013",
	"burning during urination": "s_368",
	"burning skin": "s_1165",
	"burning tongue": "s_200",
	"cafe au lait macules": "s_1330",
	"cafe au lait macules are 15mm in diameter or larger": "s_1321",
	"calcification of the tympanic membrane": "s_1168",
	"calf muscle spasms": "s_117",
	"carbohydrate consumption": "s_239",
	"cataract": "s_550",
	"ceasing or limiting alcohol consumption": "s_589",
	"chaddock sign": "s_1258",
	"change in behavior, personality or mood": "s_348",
	"change in color of a mole": "s_585",
	"change in color of a tooth": "s_346",
	"change in handwriting": "s_345",
	"change in shape of a mole": "s_584",
	"change in skin lesion (enlargement, darkening, bleeding, itching)": "s_383",
	"chemosis": "s_1091",
	"chest pain": "s_50",
	"chest pain appearing during exertion": "s_35",
	"chest pain doesn't subside after rest": "s_31",
	"chest pain increasing with deep breath or cough": "s_30",
	"chest pain lasting 2 to 5 minutes": "s_45",
	"chest pain lasting at least a few hours": "s_1204",
	"chest pain lasting longer than 30 minutes": "s_46",
	"chest pain radiating between shoulder blades": "s_37",
	"chest pain radiating to left arm": "s_1490",
	"chest pain radiating to left shoulder": "s_1489",
	"chest pain radiating to neck": "s_36",
	"chest pain subsides during rest": "s_48",
	"chest pain worsens on palpation": "s_1178",
	"chest pain, diffuse": "s_51",
	"chest pain, exacerbating during movement": "s_42",
	"chest pain, severe": "s_1197",
	"chest pain, substernal": "s_1509",
	"chest pain, sudden": "s_1200",
	"cheyne-stokes respiration": "s_1546",
	"childbirth": "s_211",
	"chills": "s_81",
	"choking during sleep": "s_78",
	"chorea": "s_1456",
	"chvostek sign": "s_867",
	"cigarette smoking": "s_195",
	"cigarette smoking during illness": "s_196",
	"clasp-knife spasticity": "s_1281",
	"claudication in buttocks and/or thighs": "s_734",
	"clearing the throat": "s_1094",
	"clicking, popping, or grating sounds in the jaw joint when opening or closing the mouth": "s_429",
	"clogged ear": "s_276",
	"close family or friends pointing out excessive drinking": "s_288",
	"club-foot": "s_869",
	"coated tonsills": "s_610",
	"coating on tongue": "s_1184",
	"cogwheel muscle rigidity": "s_1283",
	"cold foods ease toothache": "s_339",
	"cold hands or fingers": "s_556",
	"cold hands or fingers and feet": "s_408",
	"cold sensitivity": "s_118",
	"color blindness": "s_1328",
	"compensatory head tilt (in order to avoid diplopia)": "s_1230",
	"compulsive behavior": "s_303",
	"confabulation": "s_831",
	"confusion": "s_1345",
	"conjunctival pallor": "s_1212",
	"consciousness disturbances": "s_438",
	"constant need for sex": "s_181",
	"constant severe toothache": "s_240",
	"constipation": "s_329",
	"constipation, long lasting": "s_1549",
	"contact lenses": "s_499",
	"contentiousness": "s_635",
	"convergent strabismus": "s_1228",
	"convulsions or headache accompanied or preceded by buzzing or whistling": "s_260",
	"convulsions or headache preceded by olfactory hallucinations": "s_295",
	"corneal reflex weak or absent": "s_1268",
	"cornell's sign": "s_1273",
	"cough": "s_102",
	"cough lasting less than 3 weeks": "s_103",
	"cough lasting over 8 weeks": "s_106",
	"cough, attacks": "s_135",
	"cough, coughing up pink frothy sputum": "s_670",
	"cough, dry": "s_105",
	"cough, productive": "s_104",
	"couging up sputum in the morning": "s_662",
	"creaking of joint during movement": "s_270",
	"cutaneous mass, nodules": "s_548",
	"cyanosis under the eyes": "s_1105",
	"cyanosis, fingers": "s_553",
	"cyanosis, skin": "s_437",
	"cystoid macular edema": "s_1413",
	"damage to 2 separate areas of innervation": "s_1338",
	"dance's sign": "s_1555",
	"darier sign": "s_1171",
	"dark urine": "s_611",
	"dark-red spots in optic disc vessels": "s_1417",
	"daytime sleepiness": "s_131",
	"decrease of visual acuity": "s_967",
	"decreased bowel sounds": "s_1553",
	"decreased breast size": "s_357",
	"decreased breath sounds in the right basilar lung zones": "s_1395",
	"decreased libido": "s_236",
	"decreased motivation": "s_661",
	"decreased need for sleep": "s_634",
	"decreased pupillary light reflex": "s_535",
	"decreased tear production": "s_1151",
	"decreased tongue motility": "s_1277",
	"decreased vitality for at least 2 weeks": "s_356",
	"deep filling of treated tooth": "s_97",
	"deep tendon reflexes, decreased (hyporeflexia)": "s_652",
	"deep voice": "s_422",
	"deepening of periodontal pockets": "s_108",
	"delusion of guilt or sin": "s_768",
	"delusion of impoverishment": "s_774",
	"delusions of grandeur": "s_677",
	"delusions of impact": "s_680",
	"delusions of influence": "s_839",
	"delusions of persecution": "s_675",
	"delusions of reference": "s_676",
	"demarcation of retinal detachment (pigmented or nonpigmented)": "s_1409",
	"dennie-morgan fold, infraorbital fold": "s_1106",
	"dental plaque": "s_203",
	"depapillation of the tongue (loss of the lingual papillae)": "s_1394",
	"depressed mood": "s_169",
	"depressed mood, persistent": "s_916",
	"diameter of skin lesion > .25 in": "s_382",
	"diarrhea": "s_8",
	"diarrhea, foamy ": "s_412",
	"diarrhea, mainly at night": "s_1121",
	"diarrhea, rice-water": "s_1376",
	"difficulty acquiring new information": "s_269",
	"difficulty biting and chewing": "s_266",
	"difficulty bonding with infant": "s_727",
	"difficulty completely closing one eye": "s_1154",
	"difficulty determining which tooth aches": "s_267",
	"difficulty not smoking first cigarette of the day": "s_134",
	"difficulty processing visual perceptions (visual processing disorder)": "s_1034",
	"difficulty refraining from smoking cigarettes where not permitted": "s_265",
	"difficulty retracting foreskin, phimosis": "s_263",
	"difficulty urinating or defecating": "s_264",
	"diminished appetite": "s_284",
	"diminished eye motility in the same direction": "s_968",
	"diminished fear responses": "s_1035",
	"diminished or lack of eye abduction": "s_1227",
	"diminished superficial reflexes": "s_1021",
	"diplopia while looking down and medially": "s_1232",
	"diplopia while looking in any direction": "s_1235",
	"diplopia with horizontal image dispersion": "s_1229",
	"diplopia with vertical or oblique image dispersion": "s_1231",
	"discharge from ear": "s_297",
	"discharge from periodontal pockets": "s_302",
	"discharge from urethra": "s_369",
	"discharge in tympanic cavity": "s_1109",
	"discharge under foreskin": "s_301",
	"discomfort while speaking": "s_95",
	"discomfort while swallowing": "s_96",
	"disinhibition": "s_1007",
	"disorganized behavior": "s_731",
	"disorientation": "s_222",
	"disorientation in space": "s_796",
	"disorientation in time": "s_797",
	"dissociated sensory loss": "s_1265",
	"distance misjudgment": "s_501",
	"diurnal mood variation": "s_730",
	"divergent strabismus": "s_1236",
	"dizziness": "s_370",
	"double vision, diplopia": "s_207",
	"drinking alcohol at work": "s_827",
	"drinking alcohol despite awareness of harmful effects": "s_819",
	"drinking alone": "s_828",
	"drinking large quantities of alcohol": "s_198",
	"drinking large quantities of alcohol at one time": "s_199",
	"drinking to ease hangover": "s_109",
	"drooling": "s_1304",
	"drooping lower eyelid": "s_1158",
	"drooping mouth corner": "s_432",
	"drunk driving": "s_823",
	"dry cracked skin, sometimes bleeds": "s_385",
	"dry discharge on eyelids": "s_489",
	"dry mouth": "s_247",
	"dry skin": "s_542",
	"duck-like gait": "s_1225",
	"dysarthria": "s_315",
	"dysmenorrhoea": "s_59",
	"dyspepsia": "s_1432",
	"dysphagia": "s_962",
	"dysphagia to both solids and liquids": "s_1058",
	"dysphonia": "s_68",
	"dyspnea": "s_88",
	"dyspnea exacerbating during exercise": "s_1333",
	"dyspnea increasing over several hours or days": "s_90",
	"dyspnea increasing over several minutes or hours": "s_91",
	"dyspnea with flare-ups and remissions": "s_1185",
	"dyspnea, orthopnea": "s_563",
	"dyspnea, paroxysmal nocturnal": "s_1317",
	"dyspnea, sudden onset": "s_92",
	"dystonia": "s_1298",
	"ear canal swelling": "s_291",
	"earache": "s_47",
	"early waking up": "s_776",
	"edema": "s_700",
	"edema, daytime": "s_701",
	"edema, dependent": "s_699",
	"edema, face": "s_616",
	"edema, finger": "s_1311",
	"edema, hand": "s_1464",
	"edema, joint": "s_174",
	"edema, knee joint": "s_170",
	"edema, lip": "s_1433",
	"edema, lower leg": "s_173",
	"edema, lower limbs": "s_175",
	"edema, lower limbs, ankles": "s_623",
	"edema, nighttime": "s_702",
	"edema, periorbital": "s_1442",
	"edema, pitting": "s_562",
	"edema, scrotum": "s_176",
	"edema, upper limb": "s_1447",
	"edema, wrist joint": "s_1431",
	"electroneurography findings linked to demyelination": "s_751",
	"elevated body temperature with flare-ups and remissions": "s_1186",
	"elevated mood": "s_633",
	"enamel hypoplasia": "s_1166",
	"enamel lesions, caries": "s_272",
	"enlarged breasts": "s_219",
	"enlarged kidneys": "s_1052",
	"enlarged lymph nodes": "s_220",
	"enlarged salivary glands": "s_1057",
	"enlarged testicle": "s_1174",
	"enlarged thyroid": "s_364",
	"enlargement of hands, feet, face (nose, lips and ears) and a thickening of facial features": "s_480",
	"enlargement of the lymphoid tissue in the pharynx": "s_1103",
	"enlargement of tonsils": "s_1102",
	"enophthalmos - unilateral": "s_668",
	"epicritic sensation loss or impairment in fingertips": "s_1071",
	"erectile dysfunction": "s_733",
	"erythema": "s_229",
	"erythema and scaling on almost entire skin (erythroderma)": "s_1469",
	"erythema of affected limb": "s_325",
	"erythema of the foreskin and glans": "s_433",
	"erythema, and warmth of skin overlying joint": "s_323",
	"erythema, finger": "s_1314",
	"erythematous tonsils": "s_1498",
	"exacerbated by cold temperature": "s_558",
	"exacerbated by increased stress": "s_392",
	"exanthema disappears without a trace": "s_1374",
	"excess of hair": "s_132",
	"excessive fear in public situations": "s_723",
	"excessive saliva production": "s_523",
	"excessive sleepiness": "s_777",
	"excessive uterine enlargement in comparison to assumed duration of pregnancy": "s_1290",
	"excessive worry about the health of a child": "s_725",
	"exophthalmos, proptosis": "s_1163",
	"exposure to uv radiation or frequent sunburn in childhood": "s_378",
	"eye flashes": "s_606",
	"eye pain": "s_493",
	"eyelid lesion": "s_483",
	"eyelid lesion rarely hurts": "s_491",
	"eyelid tremors": "s_591",
	"eyelid twitching": "s_235",
	"facial erythema": "s_1468",
	"facial erythema, butterfly-shaped": "s_230",
	"facial muscle paresis / paralysis": "s_1156",
	"facial muscle spasms": "s_1425",
	"facial pain": "s_478",
	"facial pain, longer than a few hours": "s_1203",
	"facial pain, periodic": "s_427",
	"facial pain, severe": "s_1194",
	"facial pain, sinus": "s_1436",
	"facial pain, sudden and stabbing": "s_425",
	"facial pain, triggered": "s_426",
	"facial pain, unilateral": "s_424",
	"facial paresthesia": "s_971",
	"fainting": "s_188",
	"fainting with convulsions": "s_189",
	"fainting with urination or defecation": "s_190",
	"fear": "s_120",
	"fear of dying": "s_516",
	"fear of going insane": "s_1087",
	"fear of losing control": "s_1088",
	"fear of obesity": "s_157",
	"fear of public appearances": "s_721",
	"feeling hot": "s_274",
	"feeling of guilt or shame after drinking alcohol": "s_206",
	"feeling of guilt or worthlessness": "s_205",
	"feeling of helplessness": "s_629",
	"feeling of hopelessness": "s_632",
	"feeling of lump in throat": "s_513",
	"feeling of obstruction while swallowing": "s_278",
	"feeling of resignation": "s_507",
	"feeling of weight in scrotum": "s_1175",
	"feeling overweight despite low weight": "s_419",
	"feeling that tooth is about to explode": "s_279",
	"feeling unreal (derealization)": "s_514",
	"feet sensitive to cold": "s_296",
	"fever": "s_98",
	"fever > 101 f": "s_100",
	"fever between 99.5 and 101 f": "s_99",
	"financial recklessness": "s_636",
	"fine downy hair (lanugo)": "s_77",
	"finger pain": "s_1313",
	"first cigarette after awakening": "s_327",
	"fits of anger": "s_660",
	"flaccid dysarthria": "s_993",
	"flaccid paresis": "s_1079",
	"flares up and subsides": "s_387",
	"flat or blunted affect": "s_772",
	"foamy urine": "s_504",
	"forgets names of close friends and family": "s_146",
	"formication around the mouth": "s_126",
	"formication in feet": "s_125",
	"forward-leaning posture": "s_204",
	"foul-smelling stools": "s_525",
	"fracture of vertebra or femur without accident": "s_340",
	"frequent bowel movement": "s_1401",
	"frequent infections": "s_505",
	"frequent urinary urgency": "s_275",
	"frequent urination": "s_215",
	"frequent urination in large quantities": "s_75",
	"frontal release signs": "s_990",
	"frothy yellow-green vaginal discharge": "s_366",
	"galactorrhea": "s_547",
	"general anxiety": "s_583",
	"genital skin growths": "s_617",
	"genu varum": "s_1226",
	"glassy eyes": "s_1090",
	"goldflam sign": "s_1302",
	"gonda-allen sign": "s_1263",
	"gordon sign": "s_1254",
	"gottron's papules": "s_756",
	"grandiosity": "s_639",
	"grape-like vaginal discharge": "s_1294",
	"gum erythema": "s_322",
	"gum pain": "s_19",
	"gynecomastia": "s_586",
	"hair loss": "s_121",
	"hairy leukoplakia (epstein-barr virus, ebv)": "s_618",
	"halitosis": "s_65",
	"hallucinations": "s_686",
	"hallucinations, auditory ": "s_682",
	"hallucinations, cenesthetic": "s_685",
	"hallucinations, gustatory ": "s_683",
	"hallucinations, olfactory ": "s_684",
	"hallucinations, visual": "s_681",
	"hand erythema": "s_557",
	"hard retinal exudates": "s_1346",
	"hardening or tightness of skin on hands, face, or forearms": "s_246",
	"head drop": "s_191",
	"head injury": "s_834",
	"head injury when drunk": "s_826",
	"head tremors": "s_85",
	"headache": "s_21",
	"headache exacerbating in the morning": "s_799",
	"headache with flare-ups and remissions": "s_1188",
	"headache, anterior location": "s_1349",
	"headache, chronic ": "s_1535",
	"headache, dull": "s_1541",
	"headache, exacerbating by tilting the head forward": "s_625",
	"headache, generalized": "s_24",
	"headache, lancinating": "s_604",
	"headache, pressure": "s_23",
	"headache, pulsing": "s_25",
	"headache, series over a period of time": "s_605",
	"headache, severe": "s_1193",
	"headache, unilateral": "s_22",
	"hearing loss": "s_208",
	"hearing loss of variable intensity and duration": "s_935",
	"hearing voices arguing": "s_841",
	"hearing voices commenting": "s_840",
	"heart palpitations": "s_110",
	"heart palpitations worsen following caffeine intake": "s_1208",
	"heartburn": "s_338",
	"heavy legs at end of day": "s_273",
	"heavy menstrual periods": "s_158",
	"heliotrope rash around the eyes": "s_761",
	"hematemesis": "s_306",
	"hemianopsia bitemporalis": "s_814",
	"hemiparesis": "s_1005",
	"hemoptysis": "s_116",
	"hepatomegaly": "s_1051",
	"hiccups": "s_1295",
	"hide drinking, secret drinking": "s_829",
	"high-arched palate": "s_1108",
	"hot flashes": "s_280",
	"hyperalgesia": "s_1481",
	"hyperreflexia": "s_878",
	"hypersensitivity to sound": "s_1150",
	"hypersensitivity to stimuli": "s_133",
	"hypertension, high blood pressure": "s_543",
	"hypesthesia of half of face": "s_1159",
	"hypochondriacal delusions": "s_679",
	"hypopigmentation": "s_180",
	"hypopyon (collection of pus in the eye)": "s_570",
	"illusion of surroundings increasing or decreasing in size": "s_341",
	"impaired concentration": "s_631",
	"impaired downward eye motion": "s_1241",
	"impaired medial eye motion": "s_1240",
	"impaired memory": "s_316",
	"impaired short-term memory with long term memory maintained": "s_830",
	"impaired smell": "s_1095",
	"impaired upward eye motion": "s_1239",
	"impaired vision": "s_320",
	"impaired vision on side with painful temple": "s_1146",
	"impulsive behavior": "s_1384",
	"inability to complete tasks": "s_1385",
	"inability to maintain the same body position for a long time": "s_1024",
	"inability to move mandible sideways": "s_1300",
	"inability to pass flatus": "s_1551",
	"inability to remember important aspects of a traumatic experience": "s_711",
	"inability to stop drinking alcohol": "s_150",
	"inability to stop flow of urine": "s_223",
	"increase in sexual experiences or sensations needed to attain desired effect": "s_361",
	"increased abdominal girth": "s_218",
	"increased appetite": "s_311",
	"increased expiratory phase": "s_1488",
	"increased libido": "s_421",
	"increased masseter reflex (jaw jerk)": "s_991",
	"increased muscle tension (spasticity)": "s_571",
	"increased palatine reflex": "s_1278",
	"increased pharyngeal reflex": "s_1279",
	"increased thirst": "s_310",
	"infertility": "s_7",
	"insomnia": "s_917",
	"intense, non-committal relationships": "s_1383",
	"intermenstrual bleeding/spotting": "s_1217",
	"intermittent claudication": "s_732",
	"intermittent urine flow": "s_358",
	"intraretinal microvascular abnormalities": "s_1416",
	"intrusive thoughts - obsessive fears": "s_687",
	"intrusive thoughts - obsessive images": "s_688",
	"intrusive thoughts, obsessions": "s_127",
	"iris neovascularization": "s_1411",
	"irregular border of skin lesion": "s_381",
	"irregular menstruations": "s_1440",
	"irritability": "s_540",
	"irritability when unable to engage in activity related to sex": "s_80",
	"irritation and erythema of vulva": "s_324",
	"itching after a hot shower or bath": "s_614",
	"itching and painful eyelid lesion": "s_485",
	"itching around anus": "s_249",
	"itching blisters or wheals": "s_248",
	"itching in ear": "s_255",
	"itching of nose or throat": "s_252",
	"itching of urethral opening": "s_367",
	"jacobson sign": "s_1271",
	"jaundice": "s_332",
	"jaundice after starvation diet": "s_333",
	"jaundice during increased stress": "s_334",
	"jaundice during infectious disease": "s_336",
	"jaundice following intense physical exertion": "s_335",
	"jaw claudication": "s_1143",
	"jaw locking when opening mouth": "s_428",
	"joint malformation": "s_359",
	"joint pain": "s_44",
	"joint pain, hallux ": "s_79",
	"joint pain, knee": "s_581",
	"joint pain, metatarsalgia": "s_578",
	"joint pain, movements": "s_40",
	"joint pain, movements, mornings": "s_29",
	"joint pain, severe": "s_41",
	"joint pain, sudden": "s_1201",
	"joint pain, wrist": "s_1430",
	"joint stiffness": "s_575",
	"joint stiffness, hands, in the morning": "s_258",
	"kaposi's sarcoma nodules": "s_620",
	"kayser–fleischer ring": "s_1472",
	"koplik's spots": "s_664",
	"kussmaul breathing": "s_1451",
	"lack of boundaries in interpersonal relations": "s_778",
	"lack of initiative, motivation, drive": "s_1006",
	"lack of rest": "s_372",
	"lack of space in dental arch, crowded teeth": "s_242",
	"lack of strength in legs": "s_743",
	"large painful red nodules under skin": "s_94",
	"large quantity of cigarettes smoked": "s_93",
	"lateral hemianopsia, homonymous hemianopsia": "s_957",
	"lateropulsion": "s_964",
	"lead-pipe rigidity": "s_1282",
	"left limb-kinetic apraxia": "s_1014",
	"lengthening of reaction time": "s_658",
	"leopard-like spots": "s_666",
	"lesions are painful when pressure is applied": "s_403",
	"lesions forming a crust": "s_245",
	"lesions in different stages of development at one time": "s_399",
	"lesions on entire skin": "s_398",
	"lesions on penis": "s_349",
	"lesions on vulva": "s_353",
	"lesions preceded by pain or itching": "s_400",
	"lesions spread easily by touch": "s_375",
	"lethargy": "s_119",
	"lethargy, for more than 6 months ": "s_1547",
	"levine's sign": "s_1378",
	"lhermitte's sign": "s_1054",
	"light sensitivity": "s_488",
	"limb weakness ipsilateral to facial changes": "s_1252",
	"limbs resistant to passive movements": "s_1025",
	"limitations in everyday life activities": "s_628",
	"lisch nodules": "s_1324",
	"livedo reticularis (mottled vascular skin pattern)": "s_763",
	"local dark retinal blood vessels that lie in folds": "s_1407",
	"local elevation of retina": "s_1405",
	"local grey discoloration of retina": "s_1406",
	"local retinal undulation": "s_1408",
	"localization near sebaceous glands": "s_390",
	"localization on the border between the lips and skin": "s_401",
	"localized spread of the skin lesions": "s_406",
	"loose teeth": "s_228",
	"loss of body hair": "s_1115",
	"loss of interest in activities previously enjoyed, lasting at least 2 weeks": "s_287",
	"loss of muscle mass": "s_622",
	"loss of muscle mass in the hand/hands": "s_564",
	"loss of pain sensation in the upper pharynx": "s_1284",
	"loss of sense of vibration in distal parts of extremities": "s_1070",
	"loss of temperature sensation, impaired temperature sensation": "s_747",
	"loss of vision in a superior quadrant": "s_1027",
	"loss or impairment of proprioception": "s_746",
	"low self-esteem": "s_155",
	"low-pitched tinnitus, low-frequency tinnitus (humming, murmuring, rumbling)": "s_937",
	"lower intraocular pressure in affected eye by > 4-5mmhg in comparison to unaffected eye": "s_1404",
	"lumbar pain exacerbates during the night": "s_1339",
	"lumbar pain radiating to the groin": "s_663",
	"lump in testicle": "s_1173",
	"lying to friends and family, hiding food": "s_420",
	"maculopapular rash": "s_1301",
	"maculopapular rash, measles rash": "s_665",
	"maculopapular rash, scarlet fever rash": "s_1544",
	"making rash or impulsive decisions": "s_779",
	"malocclusions": "s_289",
	"many nevi": "s_377",
	"marcus gunn pupil": "s_1403",
	"mechanic's hand": "s_760",
	"memory loss, finding objects of everyday use": "s_619",
	"mendel-bechterev sign": "s_1261",
	"menstrual period more than 3 weeks late": "s_415",
	"miosis": "s_537",
	"miscarriage": "s_212",
	"moniz sign": "s_1274",
	"mood swings, mood instability": "s_646",
	"most cigarettes in the morning": "s_308",
	"motor retardation": "s_1297",
	"mouth breathing, breathing through mouth": "s_1104",
	"mucosal pallor": "s_1210",
	"mucous secretion in stool": "s_642",
	"multiple sexual partners": "s_294",
	"muscle cramps": "s_503",
	"muscle weakness (paresis)": "s_650",
	"muscle weakness causes difficulty climbing stairs, standing up from sitting position": "s_767",
	"myalgia": "s_1142",
	"myalgia, deep and dull": "s_748",
	"mydriasis": "s_536",
	"myringitis": "s_1476",
	"nail clubbing": "s_603",
	"nail dystrophy": "s_1167",
	"narrowing of the mouth, difficulty opening mouth": "s_360",
	"nasal catarrh": "s_107",
	"nasal congestion": "s_331",
	"nasal polyps": "s_524",
	"nasal speech": "s_1303",
	"nasopharingitis": "s_656",
	"nausea": "s_156",
	"neck asymmetry": "s_1388",
	"neck edema": "s_363",
	"neck pain": "s_1483",
	"neck pain, unilateral": "s_965",
	"neck vein distention": "s_671",
	"neglecting obligations such as work, study or family to pursue sex or think about sex": "s_326",
	"neglecting other areas of your life besides alcohol(drugs), such as hobbies, work or family": "s_820",
	"nervousness or weepiness": "s_143",
	"neural tenderness": "s_1086",
	"neuropathic arthropathy": "s_1427",
	"nihilistic delusions": "s_678",
	"nipple discharge": "s_1422",
	"nocturia": "s_182",
	"nodules on labia": "s_434",
	"non-serious eye injury": "s_495",
	"non-stop drinking for several days": "s_822",
	"nosebleeds": "s_1429",
	"numbness in one or both lower limbs": "s_1343",
	"numbness of limbs": "s_83",
	"numbness of one hand": "s_1449",
	"numbness of part of the ear": "s_1305",
	"numbness of the tongue": "s_1148",
	"numbness or spasms in arm or face muscles": "s_82",
	"numerous lesions in genital area": "s_354",
	"nystagmus": "s_479",
	"occipital headache": "s_970",
	"ocular bulb rotation laterally and downwards": "s_1237",
	"ocular bulb rotation medially and upwards": "s_1234",
	"ocular motility disorder": "s_750",
	"oculomotor nerve palsy": "s_1147",
	"oily skin": "s_362",
	"oliguria": "s_185",
	"opacified tympanic membrane": "s_1107",
	"open comedones": "s_389",
	"oppenheim sign": "s_1256",
	"optic disc neovascularization": "s_1410",
	"optic nerve disc pallor": "s_1329",
	"orbicularis oris muscle spasm": "s_868",
	"organic cause": "s_844",
	"orthostatic hypotension": "s_541",
	"outside world feels unreal (derealization)": "s_515",
	"ovarian enlargement": "s_1289",
	"overbite": "s_1110",
	"overwork": "s_371",
	"pain and redness in temporal region": "s_1145",
	"pain around nape of neck when standing": "s_409",
	"pain behind ear": "s_1180",
	"pain caused by firm pressure on sternal bone": "s_1381",
	"pain caused by firm pressure on tibia": "s_1382",
	"pain in both lower limbs": "s_1453",
	"pain in both upper limbs": "s_1452",
	"pain in both upper limbs (glove distribution)": "s_1113",
	"pain in crotch": "s_28",
	"pain in fingers": "s_554",
	"pain in glans penis": "s_60",
	"pain in lower limb": "s_579",
	"pain in lower limbs (stocking distribution)": "s_1112",
	"pain in one or both hips": "s_11",
	"pain in scrotum": "s_52",
	"pain in temporomandibular joint while yawning, chewing or biting": "s_430",
	"pain in upper limb": "s_580",
	"pain increases when touching ear area": "s_476",
	"pain is aggravated during cold, damp weather": "s_576",
	"pain near eye socket": "s_54",
	"pain radiates from buttock through back of thigh to knee": "s_38",
	"pain radiates to the right shoulder blade": "s_471",
	"pain while urinating": "s_39",
	"painful defecation": "s_1393",
	"painful ejaculation": "s_33",
	"painful intercourse": "s_32",
	"palatine petechiae": "s_1371",
	"palatine tonsil asymmetry": "s_1390",
	"pale and brittle nails": "s_10",
	"pale or clay-colored stools": "s_569",
	"pale skin": "s_9",
	"palmar erythema": "s_1125",
	"palpable abdominal mass": "s_299",
	"palpable mass in breast": "s_300",
	"palpable neck mass": "s_298",
	"panic attacks in public appearances": "s_722",
	"panic attacks triggered by stressful situation": "s_520",
	"papilledema": "s_803",
	"papillomatosis in histopatological examination": "s_895",
	"papule or abscess, boil": "s_598",
	"papules": "s_101",
	"papulo-pustular eruptions": "s_1482",
	"paralogical thinking": "s_838",
	"paralysis, limb": "s_1296",
	"paraspinal muscle tenderness": "s_1486",
	"paresis, limb": "s_148",
	"paresis, limb, upper limbs": "s_268",
	"paresthesia (body tingling)": "s_518",
	"paresthesia in both lower limbs": "s_1063",
	"paresthesia in both lower limbs (stocking distribution)": "s_1065",
	"paresthesia in both upper limbs": "s_973",
	"paresthesia in both upper limbs (glove distribution)": "s_1066",
	"parotid swelling": "s_529",
	"paroxysmal amblyopia": "s_802",
	"pencil-thin stools": "s_795",
	"pericardial friction rub": "s_1380",
	"perionychial pain": "s_1312",
	"perseveration": "s_1018",
	"petechiae (small red spots - broken capillary vessels)": "s_594",
	"pharyngeal erythema": "s_1367",
	"pharyngeal pain": "s_20",
	"pharyngeal pain when swallowing": "s_509",
	"phobia": "s_915",
	"phototype i or ii": "s_376",
	"physical trauma (to self or others) after drinking alcohol": "s_281",
	"pill rolling tremor": "s_1379",
	"pimples": "s_388",
	"pleural friction rub": "s_1396",
	"pleural serous effusion (hydrothorax)": "s_1437",
	"poikiloderma": "s_757",
	"poor personal hygiene, self-neglect": "s_770",
	"positive allergy challenge": "s_1093",
	"positive skin allergy (prick or patch) test": "s_1092",
	"post-nasal drip": "s_1471",
	"postmenopausal vaginal bleeding": "s_151",
	"poverty of speech, alogia": "s_837",
	"premature graying": "s_225",
	"preoccupation with food": "s_69",
	"presence of neurofibromas": "s_1323",
	"pretibial edema": "s_1162",
	"priapism": "s_1397",
	"problems with everyday tasks such as washing, eating, dressing": "s_123",
	"productive cough with purulent sputum": "s_526",
	"projectile vomiting": "s_801",
	"prolonged bleeding time": "s_593",
	"prostate enlargement": "s_1089",
	"pruritus": "s_254",
	"pruruitus, aggravated by change in temperature, sweating, or wool": "s_251",
	"pruruitus, most intense at night": "s_250",
	"psychomotor retardation": "s_649",
	"pulsatile tinnitus": "s_1466",
	"pupil dilation variation": "s_653",
	"pupil or pupils unreactive to accomodation": "s_1238",
	"purpuric rash": "s_762",
	"pus under the skin of the finger": "s_1315",
	"pyramidal signs": "s_989",
	"quickening of thoughts and speech": "s_637",
	"rash": "s_417",
	"rash vanishes leaving no trace": "s_395",
	"re-experiencing psychological trauma in nightmares": "s_706",
	"re-experiencing psychological trauma through physiological reactivity": "s_708",
	"re-experiencing the psychological trauma - circumstances resembling or associated with the stressor": "s_707",
	"re-experiencing the psychological trauma in recurring flashbacks": "s_705",
	"recent alcohol consumption": "s_528",
	"recent medication": "s_527",
	"receptive aphasia": "s_1029",
	"recurrent fever (about every 24, 48 or 72 hours)": "s_1172",
	"recurrent gastric ulcers": "s_142",
	"recurrent herpes simplex": "s_138",
	"recurrent kidney stones": "s_140",
	"recurrent lower respiratory tract infection": "s_532",
	"recurrent tonsils inflammation": "s_139",
	"recurrent unpleasant thoughts and images, often sexual, aggressive, killing someone, fear of getting dirty, etc": "s_141",
	"recurrent upper respiratory tract infection": "s_531",
	"red and swollen oral mucosa": "s_692",
	"red and warm eyelid lesion": "s_486",
	"red eye": "s_492",
	"red eye, stinging conjunctivae": "s_72",
	"red lump with yellow tip on eyelid": "s_484",
	"red maculas with silver-white, flaky scales": "s_384",
	"red rings with light centers on skin": "s_202",
	"red stretch marks on abdomen, hips or thighs": "s_73",
	"redness behind the ear": "s_1181",
	"redness on shoulders and nape of neck": "s_758",
	"reduced ability to maintain focus": "s_638",
	"reduced body temperature": "s_410",
	"reduced degree of facial expression (hypomimia)": "s_572",
	"reduced skin elasticity, decreased skin turgor": "s_697",
	"regurgitation": "s_330",
	"religious delusion": "s_780",
	"restless legs": "s_1463",
	"restricted mobility, problem turning the head or bending over": "s_186",
	"retinal artery occlusions": "s_1418",
	"retinal hemorrhage": "s_1344",
	"retinal microaneurysms": "s_1412",
	"retinal neovascularization elsewhere": "s_1415",
	"retinal swelling": "s_1414",
	"retraction or indentation of nipple": "s_343",
	"retrobulbar neuritis": "s_1055",
	"rhinitis triggered by environment": "s_1533",
	"rhonchi during chest auscultation": "s_1316",
	"rictus grin": "s_1375",
	"risky drinking": "s_816",
	"role, social impairment, dysfunction": "s_716",
	"rose spots on lower chest and abdomen": "s_1377",
	"rossolimo's sign": "s_1255",
	"rough and irregular skin surface": "s_404",
	"russell's sign": "s_1141",
	"sagging of the palate ipsilateral to suspected nerve damage": "s_1285",
	"schaeffer's sign": "s_1259",
	"schizophasia": "s_836",
	"scleral icterus": "s_1492",
	"scotoma, eye floaters": "s_124",
	"scratched eye": "s_498",
	"scrotal transillumination": "s_1342",
	"seasonal pattern of depressive symptoms": "s_835",
	"seizures": "s_539",
	"self-disgust after binging": "s_568",
	"sense of self-worth dependent on weight": "s_423",
	"sensory loss in both arms": "s_972",
	"sensory loss in one limb": "s_313",
	"sensory loss involving the face": "s_959",
	"severe calf pain while walking": "s_232",
	"severe pain in crotch": "s_1196",
	"severe toothache": "s_233",
	"sexual activity in recent months": "s_2",
	"sexual activity more often or with more partners than intended": "s_74",
	"sexual intercourse during fertile days": "s_413",
	"shafer's sign": "s_1399",
	"shallow breathing": "s_1462",
	"simple auditory paradelusions": "s_648",
	"simple visual paradelusions": "s_647",
	"sinus pressure": "s_1435",
	"sinuses tender to palpation": "s_1496",
	"six or more cafe au lait macules": "s_1320",
	"skin and blood vessel inflammation": "s_654",
	"skin changes with flare-ups and remission": "s_1191",
	"skin desquamation": "s_1470",
	"skin discoloration": "s_224",
	"skin lesion on palms or soles": "s_405",
	"skin lesions at point of contact with buttons or fasteners": "s_352",
	"skin lesions forming a line": "s_350",
	"skin on arm or leg hot to the touch": "s_179",
	"skin pain, severe": "s_43",
	"skin pain, severe, lasting more than a few hours": "s_49",
	"skin ulceration": "s_672",
	"skull lesions": "s_1474",
	"sleep disorder": "s_319",
	"slower gait": "s_238",
	"smooth face without wrinkles": "s_271",
	"sneeze": "s_715",
	"sneezing attacks": "s_136",
	"snoring": "s_67",
	"social isolation": "s_659",
	"social maladjustment": "s_773",
	"soft gray or flesh-colored warts or bumps": "s_63",
	"soft mass in scrotum": "s_1341",
	"soft retinal exudates": "s_1347",
	"spasmodic torticollis, cervical dystonia": "s_996",
	"spasms in upper extremities": "s_1426",
	"spastic dysarthria": "s_992",
	"spending a lot of time on sex-related activity (seeking partners, watching pornography)": "s_213",
	"spine asymmetry": "s_1536",
	"splenic agenesis": "s_1169",
	"splenomegaly": "s_1045",
	"steatorrhea": "s_1434",
	"sterling's sign": "s_1270",
	"stiff neck": "s_418",
	"stiffness of spine in the morning": "s_257",
	"stiffness subsides after exercise": "s_259",
	"stimulants use, taking stimulants (amphetamine, cocaine)": "s_880",
	"stinging conjunctivae, feeling of sand under eyelid": "s_201",
	"stransky's sign": "s_1260",
	"strawberry tongue": "s_1467",
	"stressful situation,stressor": "s_627",
	"stridor": "s_1562",
	"stroke": "s_544",
	"strumpell's sign": "s_1275",
	"sucking sensation in chest": "s_365",
	"sudden conjunctival pallor": "s_1214",
	"sudden face flushing": "s_1067",
	"sudden falls without loss of consciousness (drop attack)": "s_974",
	"sudden increase in blood pressure": "s_530",
	"sudden mucosal pallor": "s_1213",
	"sudden pain in crotch": "s_34",
	"sudden skin pallor": "s_1209",
	"suicidal thoughts": "s_1139",
	"suicidal thoughts with plan and steps taken": "s_1140",
	"sunken eyeballs": "s_698",
	"surface of lesion resembles cauliflower": "s_221",
	"sweating": "s_216",
	"sweating on forehead on painful side": "s_214",
	"sweating, night": "s_217",
	"swelling and pain in one ankle joint": "s_171",
	"swelling in the mastoid region (behind the ear)": "s_1182",
	"swelling of nasal concha": "s_1099",
	"swelling of nasal mucosa": "s_1097",
	"swelling of temporal artery": "s_1144",
	"swelling of the dorsal side (top) of the feet and around ankles": "s_1124",
	"swollen blue or bluish-gray nasal mucosa": "s_1098",
	"swollen cheek": "s_177",
	"swollen eyelid or eyelids": "s_621",
	"swollen gums": "s_172",
	"symmetrical flaccid paresis": "s_1080",
	"symmetrical flaccid paresis in lower limbs (mainly feet)": "s_1081",
	"symmetrical flaccid paresis in upper limbs (mainly hands)": "s_1082",
	"symmetrical paresthesias": "s_1068",
	"symptoms appear a few days before period": "s_161",
	"symptoms appear after taking painkillers, change in diet, under stress": "s_162",
	"symptoms do not occur during sleep": "s_602",
	"symptoms get better with physical activity": "s_599",
	"symptoms increase in the evening": "s_160",
	"symptoms occur at certain times of year or following contact with animal hair or other things": "s_167",
	"symptoms occur several hours after drinking excessive alcohol": "s_165",
	"symptoms peak 24 hours after start of menstrual period": "s_163",
	"symptoms subside when menstrual period begins": "s_164",
	"tachycardia": "s_261",
	"taste disorder in anterior two-thirds of tongue": "s_1153",
	"taste disorder in posterior one third of tongue": "s_1161",
	"taste disorders": "s_1096",
	"tearing": "s_122",
	"telangiectasias": "s_545",
	"temporary blindness": "s_1465",
	"tenderness to palpation in the right hypochondriac region": "s_1392",
	"tenderness to palpation in the umbilical region": "s_1391",
	"tenesmus": "s_640",
	"terry's nails (white nails with a dark tip)": "s_1114",
	"testicular atrophy": "s_1117",
	"thick eye discharge": "s_487",
	"thickened nails with pits or grooves": "s_386",
	"thin skin, bruises or hematomas": "s_70",
	"thoughts of harming one's child": "s_728",
	"thoughts of wanting to kill one's child": "s_729",
	"throckmorton's sign": "s_1276",
	"time spent at more than 2,500 m above sea level": "s_1149",
	"tingling fingers": "s_555",
	"tingling in extremities ipsilateral to facial changes": "s_1253",
	"tinnitus": "s_407",
	"toe-brachial index (tbi)<0.7": "s_737",
	"toenail dystrophy": "s_1085",
	"tongue enlargement": "s_673",
	"tongue erythema": "s_607",
	"tongue muscle atrophy": "s_995",
	"tongue tremors": "s_590",
	"tonic-clonic seizures": "s_1131",
	"tonsil stones": "s_1534",
	"tooth fracture": "s_283",
	"tooth loss": "s_1050",
	"tooth pain after contact with cold, sweet or hot food": "s_55",
	"tooth reacts strongly to heat": "s_231",
	"toothache": "s_551",
	"toothache while chewing": "s_56",
	"transient symptoms after consuming alcohol": "s_166",
	"transverse furrow on the nose": "s_1100",
	"tremor, flapping (asterixis)": "s_1421",
	"tremor, intention": "s_1264",
	"tremor, kinetic": "s_1454",
	"tremor, resting": "s_1455",
	"tremors": "s_538",
	"tremors in both hands": "s_87",
	"tremors in one hand": "s_86",
	"tremors subside after drinking alcohol": "s_84",
	"tremors worsen after caffeine intake": "s_601",
	"trigeminal neuralgia": "s_1056",
	"trismus (lockjaw)": "s_256",
	"tromner's sign": "s_1262",
	"trophic changes": "s_1074",
	"trophic ulcer": "s_1076",
	"trophic ulcer on the plantar side of the foot": "s_1078",
	"trouble beginning urination": "s_691",
	"trouble planning the future": "s_644",
	"trousseau sign of latent tetany": "s_866",
	"tympanic membrane light reflex distortion": "s_1366",
	"ulceration on nipple": "s_194",
	"ulcerations or abscesses near the anus": "s_351",
	"unilateral eye socket pain": "s_966",
	"unilateral facial paresis": "s_149",
	"unilateral muscular palsy, paralysis": "s_1022",
	"urethral discharge when pressing penis": "s_510",
	"urinary incontinence": "s_153",
	"urinary retention": "s_696",
	"urinary urgency": "s_690",
	"urination in small amounts": "s_689",
	"urination while coughing or laughing or during physical exertion": "s_183",
	"urticaria": "s_393",
	"urticaria triggered by cold": "s_791",
	"urticaria triggered by heat": "s_793",
	"urticaria triggered by prolonged pressure on the skin": "s_790",
	"urticaria triggered by scratching": "s_789",
	"urticaria triggered by sunlight (sun urticaria)": "s_794",
	"urticaria triggered by vibration": "s_792",
	"using methods to lose weight: vomiting, starvation diets": "s_243",
	"uvula deviates towards unaffected side during phonation": "s_1287",
	"v-shaped redness on chest": "s_759",
	"vaginal bleeding in 4 or 5 month of pregnancy": "s_1288",
	"vaginal discharge": "s_328",
	"vaginal discharge with unpleasant odor": "s_64",
	"vaginal itching and burning": "s_253",
	"verbal learning disability": "s_1031",
	"vertigo (dizziness with spinning sensation)": "s_936",
	"vesicular exanthema of mouth or ear": "s_1318",
	"violating social norms after drinking alcohol": "s_824",
	"visible and palpable enlarged vein": "s_290",
	"visual agnosia": "s_1033",
	"visual field narrowing": "s_494",
	"vitreous hemorrhage": "s_1398",
	"vomiting": "s_305",
	"vomiting less than 1h after meal": "s_307",
	"vomiting occurs more often in the morning": "s_1365",
	"vomiting on an empty stomach": "s_800",
	"vulvar itching": "s_630",
	"waist circumference for men greater than 40 in (102 cm)": "s_1215",
	"waist circumference for women greater than 35 in (88 cm)": "s_1216",
	"waist-hip ratio (whr) over 0,85 in women": "s_1219",
	"waist-hip ratio (whr) over 1,0 in men": "s_1218",
	"warts in genital area": "s_355",
	"weak eye clenching": "s_1155",
	"weak or absent palatine reflex": "s_1286",
	"weak or absent pharyngeal reflex": "s_1280",
	"weak peripheral pulses": "s_1348",
	"weak pulse in legs": "s_735",
	"weakness exacerbates after exercise": "s_1332",
	"weakness of large proximal muscles": "s_766",
	"weight gain": "s_226",
	"weight loss": "s_285",
	"weight loss without loss of appetite": "s_237",
	"weiss ring": "s_1402",
	"wheezes, sibilant rhonchi over chest": "s_856",
	"wheezing": "s_474",
	"winterbottom's sign (swelling of posterior cervical lymph nodes)": "s_1183",
	"worrisome skin lesion, itchy": "s_347",
	"worrisome skin lesions": "s_241",
	"worrisome skin lesions, appearing and disappearing quickly": "s_394",
	"worrisome skin lesions, asymmetry": "s_380",
	"worrying about health of child": "s_726",
	"wrinkling or dimpling of skin on breast": "s_342",
	"xanthelasma": "s_613"
}

var diseaseMapping = {
'Abdominal obesity': 'Obesity',
'Abducens nerve palsy': undefined,
'Acetaminophen poisoning': undefined,
'Achalasia': undefined,
'Acne': 'Acne',
'Acquired Immunodeficiency syndrome (AIDS)': 'AIDS',
'Acromegaly': undefined,
'Acute HIV infection': 'HIV/AIDS',
'Acute anticholinergic syndrome': undefined,
'Acute bronchitis': 'Bronchitis',
'Acute cholinergic syndrome': undefined,
'Acute hypnotic toxicity': undefined,
'Acute interstitial nephritis': undefined,
'Acute intestinal ischemia': 'Stomach and Intestinal Problems',
'Acute liver failure': 'Liver Cancer',
'Acute lymphoblastic leukemia (ALL)': 'Leukemia',
'Acute mastoiditis': undefined,
'Acute myeloid leukemia (AML)': 'Leukemia',
'Acute opioid (morphine, heroin) toxicity ': 'Drug Addiction',
'Acute pancreatitis': 'Pancreatic Cancer',
'Acute pharyngitis': undefined,
'Acute porphyria': undefined,
'Acute rheumatic fever': 'Rheumatism',
'Acute rhinosinusitis': undefined,
'Acute stimulant (amphetamine, cocaine) overdose': 'Drug Addiction',
'Acute thyroiditis': 'Thyroid Disorders',
'Acute tonsillitis': 'Swollen Tonsils',
'Acute viral tonsillopharyngitis': 'Swollen Tonsils',
"Addison's disease": undefined,
'Adjustment disorder': undefined,
'Adnexitis': undefined,
'African trypanosomiasis': undefined,
'Agoraphobia': undefined,
'Alcohol poisoning (ethanol toxicity)': 'Alcohol/tobacco Addiction',
'Alcohol withdrawal syndrome': 'Alcohol/tobacco Addiction',
'Alcoholic liver disease': 'Chronic Liver Disease',
'Alcoholism': 'Alcohol/tobacco Addiction',
'Allergic conjunctivitis': 'Eye Infection',
'Allergic rhinitis': undefined,
"Alzheimer's disease": "Alzheimer's Disease",
'Amebiasis': undefined,
'Amyloidosis': undefined,
'Amyotrophic lateral sclerosis': 'Multiple Sclerosis (MS)',
'Anal cancer': 'Cancer',
'Anal fissure': undefined,
'Ancylostomiasis': undefined,
'Anemia': 'Anemia',
'Anemia of chronic disease (ACD)': 'Anemia',
'Ankle osteoarthritis': 'Osteoarthritis',
'Ankylosing spondylitis': undefined,
'Anorexia': undefined,
'Antiphospholipid syndrome': undefined,
'Anxiety disorder with panic attacks': 'Panic Attacks',
'Aplastic anemia': 'Anemia',
'Appendicitis': undefined,
'Ascariasis': undefined,
'Asthma': 'Asthma',
'Atherogenic hyperlipidemia': undefined,
'Atopic dermatitis': undefined,
'Atrial fibrillation': undefined,
'Attention deficit hyperactivity disorder': 'Hyperactivity',
'Autoimmune gastritis': undefined,
'Autoimmune hepatitis': 'Hepatitis',
'Autoimmune polyendocrine syndrome type 1': undefined,
'Autoimmune polyendocrine syndrome type 2': undefined,
'Autoimmune polyendocrine syndrome type 3': undefined,
'Bacterial meningitis': 'Meningitis',
'Balanoposthitis': undefined,
"Behçet's disease": undefined,
'Benign prostatic hyperplasia': 'Enlarged Prostate',
'Beta-thalassemia': undefined,
'Bilateral frontal lobe damage': 'Head Trauma',
'Bilateral temporal lobe damage': 'Head Trauma',
'Bipolar disorder': undefined,
'Biventricular heart failure': 'Heart Disease',
'Bladder cancer': 'Cancer',
'Bleeding peptic ulcer': undefined,
'Botulism': undefined,
'Brain abscess': undefined,
'Breast cancer': 'Breast cancer',
'Brucellosis': undefined,
'Budd-Chiari syndrome': undefined,
'Bulimia': undefined,
'Cannabinoid use': undefined,
'Carbon monoxide poisoning': undefined,
'Carcinoid syndrome': undefined,
'Cardiogenic shock': undefined,
'Carotid artery dissection': undefined,
'Carotid sinus syndrome': undefined,
'Carpal tunnel syndrome': undefined,
'Cat-scratch disease': undefined,
'Cataract': 'Cataract',
'Cavernous sinus thrombosis': undefined,
'Celiac disease': 'Celiac Diseases',
'Cerebellar stroke': undefined,
'Cerebellopontine angle syndrome': undefined,
'Cerebral edema': undefined,
'Cerebral stroke': undefined,
'Cervicitis': undefined,
'Chalazion': undefined,
'Chickenpox': undefined,
'Chinese restaurant syndrome': undefined,
'Cholecystitis': undefined,
'Cholera': undefined,
'Cholestasis': undefined,
'Choriocarcinoma': undefined,
'Chronic cannabinoid use': undefined,
'Chronic constipation': 'Constipation',
'Chronic eosinophilic leukemia (CEL) and Idiopathic eosinophilia': 'Leukemia',
'Chronic fatigue syndrome': 'Extreme Fatigue/Irritability',
'Chronic interstitial nephritis': undefined,
'Chronic intestinal ischemia': undefined,
'Chronic lower limb ischemia': undefined,
'Chronic lymphocytic leukemia (CLL)': 'Leukemia',
'Chronic migraine': 'Migraines',
'Chronic myelogenous leukemia (CML)': 'Leukemia',
'Chronic obstructive jaundice': 'Jaundice',
'Chronic obstructive pulmonary disease (COPD)': 'Pulmonary Critical Care',
'Chronic pancreatitis': undefined,
'Chronic renal failure': 'Renal Failure',
'Chronic sinusitis': 'Sinusitis',
'Chronic tonsillitis': undefined,
'Chronic venous insufficiency': undefined,
'Churg-Strauss syndrome (eosinophilic granulomatosis with polyangiitis)': undefined,
'Cirrhosis': 'Cirrhosis',
'Cluster headaches (CH)': 'Headaches',
'Colon cancer (colorectal cancer)': undefined,
'Common cold': 'Common Cold',
'Conjunctivitis': undefined,
"Conn's syndrome, primary hyperaldosteronism": undefined,
'Contact dermatitis': undefined,
'Corneal abrasion': 'Corneal Abrasion (Scratch)',
'Corneal ulceration': 'Corneal Abrasion (Scratch)',
'Corticotropin releasing pituitary adenoma': undefined,
"Crohn's disease": undefined,
"Cushing's syndrome": undefined,
'Cystic fibrosis': 'Cystic Fibrosis',
'Cysticercosis': undefined,
'Cystitis (bladder infection)': undefined,
'Death cap poisoning': undefined,
'Deep vein thrombosis (DVT)': undefined,
'Degeneration of the temporomandibular joint': undefined,
'Degenerative disc disease of the cervical spine': 'Cervical Spinal Stenosis',
'Degenerative disc disease of the lumbar and sacral spine': undefined,
'Degenerative disc disease of the thoracic spine': undefined,
'Dehydration': undefined,
'Dementia': 'Dementia',
'Dengue fever': undefined,
'Dental caries': 'Lost/Missing Teeth Bad Breath',
'Dental pulp gangrene': undefined,
'Dermatomyositis': undefined,
'Diabetes insipidus (DI)': 'Diabetes',
'Diabetes mellitus type 1, type 1 diabetes, T1DM': 'Diabetes',
'Diabetes mellitus type 2, type 2 diabetes,T2DM': 'Diabetes',
'Diabetic polyneuropathy, diabetic neuropathy': 'Diabetes',
'Disulfiram-like reaction (severe alcohol intolerance)': undefined,
'Diverticulitis': undefined,
'Diverticulosis': undefined,
'Dubin-Johnson syndrome': undefined,
'Duodenal ulcer': undefined,
'Dysmenorrhea': undefined,
'Ear barotrauma': 'Ear Problems',
'Echinococcosis (echinococcal disease)': undefined,
'Ehrlichiosis': undefined,
'Empty sella syndrome': undefined,
'Endometrial cancer': undefined,
'Endometriosis': undefined,
'Enterobiasis (Pinworms)': undefined,
'Epilepsy': undefined,
'Erysipelas': undefined,
'Esophageal cancer': undefined,
'Esophageal diverticula': undefined,
'Essential thrombocytosis': undefined,
'Essential tremor': undefined,
'Extrasystoles': undefined,
'Eye movement nerve palsy (paralysis of the third, fourth, and sixth cranial nerves)': undefined,
'Facial nerve palsy': undefined,
'Fasciolosis': undefined,
'Fatigue': undefined,
'Food poisoning': undefined,
'Foot osteoarthritis': undefined,
'Gall bladder and bile duct cancer': undefined,
'Gallstone disease': undefined,
'Gastric cancer': undefined,
'Gastric ulcer': undefined,
'Gastritis': undefined,
'Gastritis due to Helicobacter pylori infection': undefined,
'Gastritis due to NSAID or corticosteroid use': undefined,
'Gastroenteritis': undefined,
'Gastroesophageal reflux disease': undefined,
'General anxiety disorder': undefined,
'Genital herpes': undefined,
'Genital warts': undefined,
'Gestational diabetes': undefined,
'Giardiasis (Beaver fever)': undefined,
"Gilbert's syndrome (Hereditary hyperbilirubinemia)": undefined,
'Gingivitis': undefined,
'Gitelman syndrome': undefined,
'Glaucoma': undefined,
'Glomerulonephritis, glomerular nephritis (GN)': undefined,
'Glossitis': undefined,
'Glossopharyngeal nerve palsy (IXth cranial nerve)': undefined,
'Gonorrhea': undefined,
"Goodpasture's syndrome": undefined,
'Gout': undefined,
"Graves' disease": undefined,
'Guillain-Barré syndrome': undefined,
"Hand osteoarthritis": undefined,
"Hashimoto's thyroiditis": undefined,
'Heat and sun-related illness': undefined,
'Hemochromatosis': undefined,
'Hemolytic anemia': undefined,
'Hemolytic-uremic syndrome (HUS)': undefined,
'Hemophagocytic lymphohistiocytosis (HLH), hemophagocytic syndrome': undefined,
'Hemophilia A': undefined,
'Hemophilia B (Christmas disease)': undefined,
'Hemorrhagic anemia': undefined,
'Hemorrhoids': undefined,
'Henoch-Schönlein purpura': undefined,
'Hepatic abscess': undefined,
'Hepatic encephalopathy': undefined,
'Hepatic failure or cirrhosis': undefined,
'Hepatitis': 'Hepatitis',
'Hepatitis A': 'Hepatitis',
'Hepatitis B': 'Hepatitis',
'Hepatitis C': 'Hepatitis',
'Herbicide poisoning': undefined,
'Herpes simplex': undefined,
'High altitude sickness': undefined,
'Hip osteoarthritis': undefined,
'Hives': undefined,
"Hodgkin's lymphoma": undefined,
"Horner's syndrome": undefined,
"Hydrocele testis": undefined,
'Hyperandrogenism': undefined,
'Hyperparathyroidism': undefined,
'Hypertension': undefined,
'Hypertensive emergency, malignant hypertension': undefined,
'Hypertensive encephalopathy': undefined,
'Hyperthyroidism': undefined,
'Hypoglycemia': undefined,
'Hypoparathyroidism': undefined,
'Hypopituitarism': undefined,
'Hypotension': undefined,
'Hypothyroidism': undefined,
'Idiopathic pulmonary fibrosis': undefined,
'Impacted wisdom tooth': undefined,
'Impetigo': undefined,
'Improper use of sleeping pills and sedatives': undefined,
'Increased intracranial pressure': undefined,
'Infectious arthritis': undefined,
'Infectious mononucleosis': undefined,
'Influenza': undefined,
'Insulinoma': undefined,
'Intercostal neuralgia': undefined,
'Interstitial acute renal failure': undefined,
'Intestinal obstruction and paralytic ileus': undefined,
'Iron deficiency anemia (IDA)': undefined,
'Irritable bowel syndrome (IBS)': undefined,
'Ischemic heart disease': 'Heart Disease',
'Kidney cancer': undefined,
'Klüver-Bucy bitemporal syndrome': undefined,
'Knee osteoarthritis': undefined,
"Korsakoff's syndrome, Korsakoff's dementia, Amnesic-confabulatory syndrome": undefined,
'Labirynthitis': undefined,
'Laryngeal cancer': undefined,
'Laryngitis': undefined,
'Lassa fever': undefined,
'Latent autoimmune diabetes of adults (LADA)': undefined,
'Lateral medullary syndrome': undefined,
'Left frontal lobe damage': undefined,
'Left-sided heart failure': 'Heart Disease',
'Legionellosis': undefined,
'Leptospirosis': undefined,
"Leriche's syndrome": undefined,
'Limbic encephalitis (LE)': undefined,
'Liver cancer': undefined,
'Lung cancer': undefined,
'Lyme disease': undefined,
'Major depressive disorder': undefined,
'Malaria': undefined,
'Manic syndrome': undefined,
'Mastocytosis': undefined,
'Measles': undefined,
'Mediastinitis': undefined,
'Medulloblastoma': undefined,
'Melanoma': undefined,
'Meningitis': undefined,
'Menopause': undefined,
'Methyl alcohol (methanol) poisoning': undefined,
'Microscopic polyangiitis': undefined,
'Middle cerebral artery syndrome': undefined,
'Migraine': undefined,
'Mild Cognitive Impairment (MCI)': undefined,
'Milk-alkali syndrome': undefined,
'Mixed connective tissue disease': undefined,
'Molar pregnancy': undefined,
'Mononeuritis multiplex': undefined,
"Multiple endocrine neoplasia type 1 (MEN1), Wermer's syndrome": undefined,
"Multiple endocrine neoplasia type 2A (MEN2A), Sipple's syndrome": undefined,
"Multiple endocrine neoplasia type 2B (MEN2B)": undefined,
'Multiple myeloma': undefined,
'Multiple sclerosis (MS)': undefined,
'Mumps (epidemic parotitis)': undefined,
'Myasthenia gravis': undefined,
'Myelofibrosis, Myeloid metaplasia': undefined,
'Myocardial infarction': undefined,
'Myocarditis': undefined,
"Ménière's disease": undefined,
"Ménétrier's disease (giant hypertrophic gastritis)": undefined,
'Nasal polyps': undefined,
'Nephritis': undefined,
'Nephrolithiasis': undefined,
'Nephrotic syndrome': undefined,
'Nicotine dependence': undefined,
'No ST Elevation Myocardial Infarction': undefined,
'Non-Hodgkin lymphoma (NHL)': undefined,
'Nonallergic noninfectious rhinitis': undefined,
'Obesity': 'Obesity',
'Obsessive-compulsive disorder': undefined,
'Obstructive jaundice': undefined,
'Oculomotor nerve palsy': undefined,
'Orchitis and epididymitis': undefined,
'Osteomalacia': undefined,
'Osteoporosis': undefined,
'Otitis externa': undefined,
'Otitis media': undefined,
'Ovarian cancer': undefined,
"Paget's disease of bone": undefined,
"Pancoast tumor": undefined,
'Pancreatic cancer': undefined,
'Paranoid schizophrenia': undefined,
"Parkinson's disease": undefined,
'Paronychia': undefined,
'Paroxysmal nocturnal hemoglobinuria': undefined,
'Peptic ulcer': undefined,
'Pericarditis': undefined,
'Periodontitis': undefined,
'Peripheral neuropathy': undefined,
'Peritonitis': undefined,
'Peritonsillar abscess (quinsy)': undefined,
"Pernicious anemia, Biermer's anemia": undefined,
'Personality disorder': undefined,
'Pesticide poisoning': undefined,
'Pheochromocytoma': undefined,
'Pituitary prolactin releasing adenoma': undefined,
'Pituitary somatotropin releasing tumor': undefined,
'Pituitary tumor': undefined,
'Placental site trophoblastic tumour': undefined,
'Plague': undefined,
'Plummer-Vinson syndrome, sideropenic dysphagia': undefined,
'Pneumonia': undefined,
'Pneumothorax': undefined,
'Polyarteritis nodosa': undefined,
'Polycystic ovary syndrome': undefined,
'Polycythemia vera': undefined,
'Polymyositis': undefined,
'Post-traumatic stress disorder': undefined,
'Postconcussional syndrome': undefined,
'Postpartum depression': undefined,
'Pre-eclampsia': undefined,
'Pregnancy': undefined,
'Premenstrual syndrome (PMS)': undefined,
'Prerenal acute renal failure': undefined,
'Presbycusis': undefined,
'Primary biliary cirrhosis': undefined,
'Primary sclerosing cholangitis (PSC)': undefined,
"Prinzmetal's angina": undefined,
'Progressive supranuclear palsy (PSP)': undefined,
'Prostate cancer': 'Prostate Symptoms',
'Prostatitis': undefined,
'Pseudo-Tetany': undefined,
'Pseudobulbar palsy': undefined,
'Pseudobulbar syndrome with acute vestibulopathy': undefined,
'Pseudomembranous colitis': undefined,
'Psittacosis (parrot fever, ornithosis)': undefined,
'Psoriasis': undefined,
'Psychotic depression': undefined,
'Psychotic mania': undefined,
'Pulmonary edema': undefined,
'Pulmonary embolism': undefined,
'Pulmonary hypertension': undefined,
'Pulpitis': undefined,
'Pure hypercholesterolemia': undefined,
'Pure hypertriglyceridemia': undefined,
'Pyelonephritis': undefined,
'Q fever': undefined,
'Ramsay Hunt syndrome type II': undefined,
"Raynaud's phenomenon": undefined,
'Reactive arthritis': undefined,
'Recurrent laryngeal nerve paralysis': undefined,
"Reiter's syndrome": undefined,
"Relapsing fever": undefined,
'Respiratory failure': undefined,
'Retinal detachment': undefined,
'Retinopathy': undefined,
'Rheumatoid arthritis': undefined,
'Rift Valley fever  (RVF)': undefined,
'Right frontal lobe damage': undefined,
'Right temporal lobe damage': undefined,
'Right-sided heart failure': undefined,
'Rocky Mountain spotted fever (RMSF)': undefined,
'Rotor syndrome': undefined,
'Rubella': undefined,
'ST elevation myocardial infarction (STEMI)': undefined,
'Salicylate poisoning': undefined,
'Sarcoidosis': undefined,
'Scabies': undefined,
'Scarlet fever': undefined,
'Schizoaffective disorder - depressive type': undefined,
'Schizoaffective disorder - manic type': undefined,
'Sciatica': undefined,
'Scoliosis': undefined,
'Scrub typhus (Bush typhus)': undefined,
'Scurvy': undefined,
'Seasonal affective disorder': undefined,
'Seborrheic dermatitis': undefined,
'Sexual addiction': undefined,
'Shigellosis, Bacillary dysentery': undefined,
'Shingles': undefined,
'Sickle cell anemia': undefined,
"Sjögren's syndrome": undefined,
'Skeletal limb trauma': undefined,
'Sleep apnea': undefined,
'Sleep apnea, obstructive': undefined,
'Small intestinal bacterial overgrowth': undefined,
'Social anxiety disorder': undefined,
'Specific phobia': undefined,
'Spinal osteoarthritis': undefined,
'Stable angina pectoris': undefined,
'Stress incontinence': undefined,
'Stye': undefined,
'Sudden sensorineural hearing loss (SSNHL, ISSNHL)': undefined,
'Superficial phlebitis': undefined,
'Superior vena cava syndrome (SVCS)': undefined,
'Syndrome of inappropriate antidiuretic hormone secretion (SIADH)': undefined,
'Systemic lupus erythematosus': undefined,
'Systemic scleroderma': undefined,
'Taeniasis': undefined,
"Takayasu's disease": undefined,
"Temporal giant cell arteritis (GCA)": undefined,
'Tension-type headaches': undefined,
'Testicular cancer': 'Testicular Pain',
'Testicular torsion': 'Testicular Pain',
'Tetanus': undefined,
'Tetany': undefined,
'Thoracic outlet syndrome (TOS)': undefined,
'Thrombocytopathy': undefined,
'Thrombotic thrombocytopenic purpura (TTP)': undefined,
'Thymoma': undefined,
'Thyroid cancer': 'Thyroid Disorders',
'Thyrotoxicosis': undefined,
'Thyrotropin releasing pituitary adenoma': undefined,
'Toxocariasis': undefined,
'Transient ischemic attack (TIA)': undefined,
'Trichinosis': undefined,
'Trichomoniasis': undefined,
'Trichuriasis': undefined,
'Trigeminal nerve damage': undefined,
'Trigeminal neuralgia': undefined,
'Trochlear nerve palsy (IVth cranial nerve)': undefined,
'Trypanosomiasis (Chagas disease, South American trypanosomiasis)': undefined,
'Tuberculosis': 'Tuberculosis',
'Tuberculous meningitis (TBM)': undefined,
'Tularemia': undefined,
'Tumor lysis syndrome': undefined,
'Type 1 Neurofibromatosis': undefined,
'Type 2 Neurofibromatosis': undefined,
'Typhoid, Typhoid fever': undefined,
'Typhus or Epidemic typhus': undefined,
'Ulcerative colitis': undefined,
'Unilateral frontal lobe damage': undefined,
'Urethritis': undefined,
'Urge incontinence': undefined,
'Urinary tract infection (UTI)': undefined,
'Uterine cancer': undefined,
'Uterine fibroids': undefined,
'Uveitis': undefined,
'VIPoma, Verner-Morrison syndrome': undefined,
'Vaginitis': undefined,
'Vagus nerve palsy (Xth cranial nerve)': undefined,
'Vascular hemorrhagic diathesis': undefined,
'Vasculitis': undefined,
'Vertebrobasilar insufficiency': undefined,
'Vestibulocochlear nerve damage (VIIIth cranial nerve)': undefined,
'Viral meningitis': undefined,
'Visceral leishmaniasis (kala-azar, black fever)': undefined,
'Vitamin B12 deficiency anemia': undefined,
'Von Willebrand disease': undefined,
'Vulvar cancer': undefined,
'Vulvar cysts': undefined,
"Waldenström's macroglobulinemia": undefined,
'Warts': undefined,
'Water poisoning': undefined,
"Wegener's granulomatosis": undefined,
"Wernicke's encephalopathy": undefined,
"Whipple's disease": undefined,
'Whitlow': undefined,
"Wilson's disease": undefined,
'Wiskott-Aldrich syndrome': undefined,
'Withdrawal syndrome (sedatives)': undefined,
'Yellow fever': undefined,
'Zollinger-Ellison syndrome, gastrinoma': undefined,
"de Quervain's thyroiditis (subacute granulomatous thyroiditis, Giant Cell Thyroiditis)": undefined
}